# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tdwl9q6wORCex4ov4y3zgFBhq24U8FBV
"""

import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer, DistilBertModel # Updated import

#skiprows=range(1, 5101)

# Step 2: Load the CSV file
csv_path = '/content/drive/MyDrive/CMU MOSEI/Audio/Raw4/Raw4-2/train.csv'  # Replace with the path to your CSV file
df = pd.read_csv(csv_path,skiprows=range(1, 801),nrows = 500) #4755

# Assume the text data is in a column named 'text'
texts = df['text'].tolist()

# Step 3: Tokenize the text data
# Using AutoTokenizer to infer the correct tokenizer for DistilBERT
tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased')
tokens = tokenizer(texts, padding='max_length', truncation=True,max_length=355, return_tensors="pt")

# Step 4: Pass the tokenized data through DistilBERT
model = DistilBertModel.from_pretrained('distilbert-base-uncased')
with torch.no_grad():
    outputs = model(**tokens)

# We are interested in the last hidden state
last_hidden_states = outputs.last_hidden_state

# Step 5: Save the output to Google Drive
output_path = '/content/drive/MyDrive/CMU MOSEI/Audio/Raw4/Distil/train3.npy'  # Replace with your desired output path in Google Drive
np.save(output_path, last_hidden_states.numpy())

print(f"Output saved to {output_path}")